### ISSUE TITLE
Where can I download the style file ?

### ISSUE THREAD

**Issue by moonsh** [cifkao/groove2groove#13]
I downloaded the data set you shared via this website : [https://zenodo.org/record/3958000#.YNG5YXUzaV4]

I found this midi file like "maj500.BRITROK8_b.midi"

I guess maj500 is content and BRITROK8 is a style file. 
And this midi file is an output of style embedding. Is that correct?

But not sure why there is a substyle a or b.
Could you explain this?
and where can I download the style file BRITROK8?

Thank you

**Comment by cifkao** [comment]
`maj500` would be the name of the chord chart, you can find it under `charts/test/abc/maj500.abc`. `BRITROK8` is the name of a Band-in-a-Box (BIAB) style – it comes with BIAB and you need BIAB/RealBand to use it. And `maj500.BRITROK8_b.mid` is the accompaniment produced by BIAB when given this chord chart as input and with the BRITROK8 style selected.

Band-in-a-Box styles moreover contain two substyles, which you can switch between in your chord chart. For example, you could use the A substyle for the first part of the song and the B substyle for the second part of the song. Here, we just use a single substyle for the whole chord chart, that's why we append the name of the substyle to the filename.
