### ISSUE TITLE
Is there the data preprocess code to band in a box?

### ISSUE THREAD

**Issue by Chenfei-Kang** [cifkao/groove2groove#18]
I have download Band-in-a-box and refer to https://github.com/cifkao/pybiab. But there are still some problem that I can't fix. For example, I find the generation result from Real-Band is a little different every time. There are different notes every time I save the same song with the same style. And how to fix the wrong program number in MIDI files?
Thank you very much!

**Comment by cifkao** [comment]
> I find the generation result from Real-Band is a little different every time. There are different notes every time I save the same song with the same style.

Yes, this is a feature of the RealBand algorithm. It's randomized, so you will get a different result every time. I'm not aware of a way to fix the random seed. Why do you want to get the same result every time? Because of reproducibility?

> And how to fix the wrong program number in MIDI files?

Try this script: https://github.com/cifkao/groove2groove/blob/master/code/groove2groove/scripts/fix_rb_midi.py

**Comment by Chenfei-Kang** [comment]
> > I find the generation result from Real-Band is a little different every time. There are different notes every time I save the same song with the same style.
> 
> Yes, this is a feature of the RealBand algorithm. It's randomized, so you will get a different result every time. I'm not aware of a way to fix the random seed. Why do you want to get the same result every time? Because of reproducibility?
> 
> > And how to fix the wrong program number in MIDI files?
> 
> Try this script: https://github.com/cifkao/groove2groove/blob/master/code/groove2groove/scripts/fix_rb_midi.py

Thank you!
